base: /
title: charon
description: this is test create doc
host: 0.0.0.0
port: 3333
head:
- ['link', {rel: 'icon', href: 'logo_zi.png'}]
themeConfig:
  logo: logo_zi.png
  nav:
  -
    text: Home
    link: /
  -
    text: External
    link: /github.com
    target: _blank

  sidebar:
    /:
    /charon:
    - charon.log
    - charon.error
    - charon.warn
  displayAllHeaders: true
  activeHeaderLinks: false
  search: true

plugins:
  - '@vuepress/plugin-back-to-top'